### ISSUE TITLE
Unresolved import when using "from parse_it import ParseIt"

### ISSUE THREAD

**Issue by LyonsDo** [naorlivne/parse_it#81] opened 2020-08-15 07:59 UTC
## Expected/Wanted Behavior
I've tried adding the parse_it to my venv using pip and Poetry.  They both seem to show it as being there.

pip install parse-it
Collecting parse-it
  Using cached parse_it-3.4.0-py3-none-any.whl (27 kB)
Processing c:\users\donal\appdata\local\pip\cache\wheels\bc\f8\ae\bc69cb5f61393ebf9ade4cde41d1a813d35bfe78263a26f99e\dpath-2.0.1-py3-none-any.whl
Collecting xmltodict
  Using cached xmltodict-0.12.0-py2.py3-none-any.whl (9.2 kB)
Collecting python-dotenv
  Using cached python_dotenv-0.14.0-py2.py3-none-any.whl (17 kB)
Requirement already satisfied: PyYAML in c:\users\donal\source\repos\tb1\venv\lib\site-packages (from parse-it) (5.3.1)
Processing c:\users\donal\appdata\local\pip\cache\wheels\0d\c4\19\13d74440f2a571841db6b6e0a273694327498884dafb9cf978\configobj-5.0.6-py3-none-any.whl
Processing c:\users\donal\appdata\local\pip\cache\wheels\ab\bd\51\063758347c589aaf729d573fd51ea4cd962ea5a498be1a8bcc\pyhcl-0.4.4-py3-none-any.whl
Collecting toml
  Using cached toml-0.10.1-py2.py3-none-any.whl (19 kB)
Requirement already satisfied: six in c:\users\donal\source\repos\tb1\venv\lib\site-packages (from configobj->parse-it) (1.15.0)
Installing collected packages: dpath, xmltodict, python-dotenv, configobj, pyhcl, toml, parse-it
Successfully installed configobj-5.0.6 dpath-2.0.1 parse-it-3.4.0 pyhcl-0.4.4 python-dotenv-0.14.0 toml-0.10.1 xmltodict-0.12.0

## Actual Behavior
Unresolved import

## Steps to Reproduce the Problem

  1. pip install parse_it
  2. And/Or poetry add parse_it
  3.

## Specifications

Python version: 
(3.5 & higher required, lower versions may work but will not be tested against)
3.7.64

parse_it version:
Current

OS type & version:
Windows 10 Pro.  Current.

MS Visual Studio 2019.

**Comment by LyonsDo** [comment] 2020-08-15 08:02
What I actually want to do is to iterate through all the sections of a TOML file, pick out the K/V pairs and write them to a Mem cache.

**Comment by naorlivne** [comment] 2020-08-15 12:46
I Retested it locally (as well as the automated build tests) and can confirm it works so the reason must be the differences between your machine & mine/the CI/CD containers, I can spot one major difference with the info provided that might explain it and that is that your using Windows rather then Linux/Mac.

Unfortunately I don't have a windows machine so can't test it myself but I have a guess as to what might be the root cause you can try:

I noticed you ran `pip install parse-it` and not `pip install parse_it` as the documentation recommends (notice the underscore rather then dash), can you try uninstalling the currently installed `parse-it` and  running `pip install parse_it` and see if it helps? I'm unfamiliar with how windows handles Python package installation but if it uses package naming as part of it's dir structure that might explain it

**Comment by LyonsDo** [comment] 2020-08-15 13:20
Thanks for the reply.  This a.m. I narrowed it down to a Visual Studio
problem!  Waiting for a reply from them.

What you've written is nice :-(

Donal.

**Comment by naorlivne** [comment] 2020-08-15 15:25
Seeing how you tracked it down to an issue that's outside of Parse_it I'm gonna close this ticket.

**Closed by naorlivne** 2020-08-15 15:25 UTC
Labels: bug
